### ISSUE TITLE
總整與排版

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#21]
## TODO
- [x] 文件排版
- [x] 格式統一
- [ ] 弄好再叫我去標記參考資料
## 備註
- 以下這個排序應該是 100% 正確的排序
- 有缺少的再跟我說, 或是你覺得排在合理的地方
- 操作說明書的工作指派給雷 #27 
- 主體 = 文獻 + SA + 演算
- 附件 = SD + test + 領頭羊資料 + javascript demo
- 環境圖于雅還沒弄 #7 

---
### 文獻
- [x] 緒論 1
- [x] SPA 2.1
- [x] JS ES6 2.2
- [x] RESS 2.3
- [x] Git 2.4
- [x] RESTful APi 2.5
- [x] Node.js 2.6
- [x] TDD, BDD 2.7
### SA 4
- [ ] 環境圖 4.1
- [x]  系統架構圖4.2 [IMG](https://goo.gl/ujKU5z)
- [x] React.js 元件架構圖4.3 
- [x] 元件說明4.3.1 [GoogleDrive](https://docs.google.com/document/d/1KXOdxUDqEaSZ8tEhVeOGPCrjj74FP02aPLvvB_WRkTA/edit)
- [x] Flux 資料流程圖4.4
- [x] Flux 實作圖 ( 小張 )4.4.1
- [x] Flux 實作圖 ( 超大那張 )
- [x] API 文件4.5
- [x] DB 解說4.6
- [x] DB shcema4.6.1
### 演算法 5
- [x] 介紹
- [x] 驗證
### SD
- [x] 先前的 電腦版 設計圖 A
- [x] 先前的 行動裝置 設計圖 B
### 測試結果報告
- [x] 報告 C
### MongoDB安裝教學
- [x] 安裝手冊 D
### Node.js安裝教學
- [x] 安裝手冊 E
### 演算法附件資料
- [x] 領頭羊心得報告 F
- [x] 使用者心得報告 G
### JS ES6
- [x] 範例：同步物件 H
- [x] 範例：回調函數 I

**Comment by andrewchen30** [comment]
@keami326  幫我確認一下有沒有任何問題
直接按右上角的鉛筆就可以修改了
修改的時候注意一下我寫的格式XD
照著就會有一樣的效果

**Comment by keami326** [comment]
文獻裡的 "SPA" 是??

**Comment by andrewchen30** [comment]
Single Page App :"D

**Comment by andrewchen30** [comment]
@keami326  除了 React 元件說明之外，全部的資料已經更新上去
新的版本於此 -> [專題文件.docx](https://github.com/PolarBearAndrew/CodePioneer/files/77458/default.docx)

**Comment by q3856245** [comment]
我是璇，我已經寄給你了，在FB專題，有word、pdf兩個檔

**Comment by andrewchen30** [comment]
:+1:

**Comment by andrewchen30** [comment]
ok 了
